import type { Venue } from '@/lib/solana/constants';

export type { Venue };

export type WhaleTier = 'shrimp' | 'dolphin' | 'whale' | 'kraken';
export type TradeSide = 'buy' | 'sell';
export type AlertSeverity = 'info' | 'warning' | 'critical';
export type AlertType =
  | 'new_position'
  | 'large_buy'
  | 'large_sell'
  | 'full_exit'
  | 'rotation'
  | 'cluster_buy'
  | 'pumpfun_snipe'
  | 'whale_discovered';

export interface MemeToken {
  mint: string;
  symbol: string;
  name: string | null;
  decimals: number;
  logo_uri: string | null;
  source: 'manual' | 'core' | 'pumpfun' | 'birdeye' | 'auto';
  is_core: boolean;
  is_active: boolean;
  price_usd: number | null;
  market_cap_usd: number | null;
  liquidity_usd: number | null;
  volume_24h_usd: number | null;
  price_change_24h: number | null;
  holder_count: number | null;
  pumpfun_created_at: string | null;
  pumpfun_graduated: boolean;
  first_seen_at: string;
  last_refreshed_at: string | null;
  created_at: string;
}

export interface Whale {
  address: string;
  label: string | null;
  portfolio_value_usd: number;
  meme_value_usd: number;
  meme_exposure_pct: number;
  trade_count_30d: number;
  avg_trade_size_usd: number;
  max_trade_size_usd: number;
  realized_pnl_usd: number;
  win_rate: number | null;
  distinct_tokens_30d: number;
  score: number;
  tier: WhaleTier;
  discovery_source: string | null;
  is_tracked: boolean;
  last_signature: string | null;
  first_seen_at: string;
  last_active_at: string | null;
  last_synced_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface WhaleTrade {
  id: string;
  signature: string;
  whale_address: string;
  slot: number | null;
  block_time: string;
  side: TradeSide;
  venue: Venue;
  token_mint: string;
  token_symbol: string | null;
  token_amount: number;
  quote_mint: string | null;
  quote_symbol: string | null;
  quote_amount: number | null;
  usd_value: number;
  price_usd: number | null;
  is_new_position: boolean;
  is_full_exit: boolean;
  /** Cost of the sold tokens, from observed buys. Null when basis is unknown. */
  cost_basis_usd: number | null;
  /** Profit/loss on a sell. Null for buys and for unknown-basis sells. */
  realized_pnl_usd: number | null;
  realized_pnl_pct: number | null;
  raw: unknown;
  created_at: string;
}

export interface PortfolioHolding {
  whale_address: string;
  token_mint: string;
  token_symbol: string | null;
  amount: number;
  usd_value: number;
  price_usd: number | null;
  pct_of_portfolio: number | null;
  is_meme: boolean;
  snapshot_at: string;
}

export interface Alert {
  id: string;
  type: AlertType;
  severity: AlertSeverity;
  whale_address: string | null;
  token_mint: string | null;
  token_symbol: string | null;
  title: string;
  message: string;
  usd_value: number | null;
  signature: string | null;
  metadata: Record<string, unknown> | null;
  created_at: string;
  /** Generated by Postgres; never written by the app. */
  dedupe_key?: string;
}

export interface TokenLeaderboardRow {
  mint: string;
  symbol: string;
  name: string | null;
  logo_uri: string | null;
  price_usd: number | null;
  market_cap_usd: number | null;
  liquidity_usd: number | null;
  volume_24h_usd: number | null;
  price_change_24h: number | null;
  whale_count_24h: number;
  whale_buy_usd_24h: number;
  whale_sell_usd_24h: number;
  net_flow_usd_24h: number;
  whale_trades_24h: number;
  new_positions_24h: number;
  last_trade_at: string | null;
}

/** A swap decoded from chain data, before it is priced and persisted. */
export interface ParsedSwap {
  signature: string;
  slot: number;
  blockTime: Date;
  wallet: string;
  side: TradeSide;
  venue: Venue;
  tokenMint: string;
  tokenAmount: number;
  quoteMint: string | null;
  quoteAmount: number | null;
}

/** Wallet-level stats used by the whale scorer. */
export interface WalletMetrics {
  address: string;
  portfolioValueUsd: number;
  memeValueUsd: number;
  memeExposurePct: number;
  tradeCount30d: number;
  avgTradeSizeUsd: number;
  maxTradeSizeUsd: number;
  distinctTokens30d: number;
  realizedPnlUsd: number;
  winRate: number | null;
  lastActiveAt: Date | null;
}

export interface WhaleScore {
  score: number;
  tier: WhaleTier;
  qualifies: boolean;
  /** Human-readable breakdown, useful for debugging why a wallet was rejected. */
  reasons: string[];
  components: {
    portfolio: number;
    tradeSize: number;
    frequency: number;
    memeExposure: number;
    diversity: number;
  };
}

export interface ApiListResponse<T> {
  data: T[];
  count: number;
  page: number;
  pageSize: number;
  hasMore: boolean;
}

export interface OhlcvCandle {
  unixTime: number;
  o: number;
  h: number;
  l: number;
  c: number;
  v: number;
}
